name = "XAML"
grammar = "xml"
path_suffixes = ["xaml"]
# Look for common XAML root elements like Window, UserControl, or Application
first_line_pattern = '^<.(Window|Application|Page|ContentPage|UserControl|ResourceDictionary|ScrollView )'
block_comment = ["<!-- ", " -->"]
brackets = [{ start = "<", end = ">", close = true, newline = true }]
# For Prettier treat xaml as plain xml
prettier_parser_name = "xml"
prettier_plugins = ["@prettier/plugin-xml"]
